### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by Carly-Schaaf** [saskatchuwan/lambda-music#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the form adjusts properly (input boxes move up, sign in/sign up button moves down, and errors are displayed in between)
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by Carly-Schaaf** [comment]
You can go ahead and check off any items that are finished! I won't be able to close the issue until you push to Heroku and update the live link on your wiki with the actual link, so be sure to update the link after the push party today. But feel free to move on in the meantime!

**Comment by saskatchuwan** [comment]
Demo link is updated.

**Comment by Carly-Schaaf** [comment]
Looks great! One thing:
- [x] Your signup errors seem to be the same as your login errors. You should make them reflect what the user did incorrectly when trying to sign up (e.g. password too short, etc.).

**Comment by saskatchuwan** [comment]
Updated the errors rendered in sign up!
